DeepEval Agentic Metrics Evaluation

This project validates an AI agent workflow using DeepEval agentic metrics.

An agent usually does:
user request
→ plans or decides steps
→ selects tools
→ calls tools
→ uses tool results
→ gives final answer

Agentic metrics check:
- Did the agent complete the task?
- Did the agent choose the correct tool?
- Did the agent pass correct arguments?
- Did the agent follow the plan?
- Did the agent avoid unnecessary steps?

This project evaluates AI agent behavior using DeepEval agentic metrics.

In [1]:
!pip install deepeval groq -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 601.5/601.5 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 1.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
huggingface-hub 1.28.0 requires click<9.0.0,>=8.4.2, but you have click 8.3.3 which is incompatible.

In [2]:
import os
from google.colab import userdata
from groq import Groq

from deepeval.models import DeepEvalBaseLLM

In [3]:
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")


class GroqDeepEvalModel(DeepEvalBaseLLM):

    def __init__(self, model_name="openai/gpt-oss-20b"):
        self.model_name = model_name
        self.client = Groq(api_key=os.environ["GROQ_API_KEY"])

    def load_model(self):
        return self.client

    def generate(self, prompt: str, **kwargs) -> str:
        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {
                    "role": "system",
                    "content": "Return only valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        return response.choices[0].message.content

    async def a_generate(self, prompt: str, **kwargs) -> str:
        return self.generate(prompt, **kwargs)

    def get_model_name(self):
        return self.model_name


groq_model = GroqDeepEvalModel()

print("Groq evaluator connected.")

Groq evaluator connected.

In [4]:
from google.colab import files

uploaded = files.upload()

Saving agent.py to agent.py

In [5]:
from agent import support_agent

print("Real agent imported successfully.")

Real agent imported successfully.

In [11]:
from deepeval.dataset import Golden, EvaluationDataset
from deepeval.test_case import ToolCall

agent_goldens = []

for _, row in agent_df.iterrows():
    agent_goldens.append(
        Golden(
            input=row["user_task"],
            expected_output=row["expected_outcome"],
            expected_tools=[
                ToolCall(name=str(row["expected_tools"]).strip())
            ],
        )
    )

agent_dataset = EvaluationDataset(goldens=agent_goldens)

print("DeepEval dataset created.")
print("Total test cases:", len(agent_goldens))

DeepEval dataset created.
Total test cases: 35

In [12]:
from deepeval.metrics import ToolCorrectnessMetric

tool_correctness_metric = ToolCorrectnessMetric()

print("Tool Correctness metric created.")

DeepEvalError: OpenAI API key is not configured. Set OPENAI_API_KEY in your environment or pass `api_key` to OpenAIModel(...).

In [6]:
from deepeval.dataset import Golden, EvaluationDataset
from deepeval.evaluate import ErrorConfig, AsyncConfig
from deepeval.tracing import observe, update_current_trace
from deepeval.metrics import TaskCompletionMetric, StepEfficiencyMetric, ToolCorrectnessMetric, ArgumentCorrectnessMetric, PlanQualityMetric, PlanAdherenceMetric

### TaskCompletionMetric

TaskCompletionMetric checks whether an AI agent successfully completed the user’s task.

It focuses on the final outcome of the agent’s work.

If the agent’s response fully satisfies the user request, it passes.

If the agent gives only partial help, unclear help, or does not complete the requested task, it fails.

In [7]:
task_completion_metric = TaskCompletionMetric(
    threshold=0.6,
    model=groq_model,
    include_reason=True
)

print("Task Completion metric created.")

Task Completion metric created.

In [9]:
import pandas as pd

agent_df = pd.read_csv("agentic_metrics_dataset.csv")

print("Agentic metrics dataset loaded.")
print("Total test cases:", len(agent_df))

display(agent_df.head())

Agentic metrics dataset loaded.
Total test cases: 35

,test_id,user_task,expected_outcome,expected_plan,expected_tools,expected_arguments,actual_output,actual_tools,actual_arguments
0,AGENT_TC_001,I placed order ORD1001 yesterday. How can I tr...,Provide clear tracking guidance for ORD1001 us...,Identify order tracking intent; extract ORD100...,track_order_tool,"{""order_id"": ""ORD1001""}",Order ORD1001 can be tracked using the trackin...,track_order_tool,"{""order_id"": ""ORD1001""}"
1,AGENT_TC_002,The product is unused and I bought it 15 days ...,Confirm refund eligibility for an unused produ...,Identify refund eligibility intent; check prod...,refund_policy_tool,"{""product_condition"": ""unused"", ""days_since_pu...",An unused product in original condition can be...,refund_policy_tool,"{""product_condition"": ""unused"", ""days_since_pu..."
2,AGENT_TC_003,My order ORD1003 has not shipped yet. I need t...,Explain that the address can be changed before...,Identify address-change intent; extract ORD100...,change_address_tool,"{""order_id"": ""ORD1003"", ""shipment_status"": ""no...",Delivery address for order ORD1003 can be chan...,change_address_tool,"{""order_id"": ""ORD1003"", ""shipment_status"": ""no..."
3,AGENT_TC_004,"I already paid for ORD1004, but it has not bee...",Confirm cancellation is possible before shippi...,Identify cancellation intent; extract order/pa...,cancel_order_tool,"{""order_id"": ""ORD1004"", ""payment_status"": ""pai...",Order ORD1004 can be cancelled before shipping...,cancel_order_tool,"{""order_id"": ""ORD1004"", ""payment_status"": ""pai..."
4,AGENT_TC_005,"Money was deducted from my account, but I did ...",Ask for transaction details and guide the user...,Identify payment failure intent; call payment_...,payment_issue_tool,"{""issue_type"": ""payment_deducted_order_not_cre...",If payment was deducted but the order was not ...,payment_issue_tool,"{""issue_type"": ""payment_deducted_order_not_cre..."

This approach is used when QA does not have access to the live agent source code or tracing callbacks. In that case, actual_tools and expected_tools can be compared from logs/CSV.

If agent source code is available, ToolCorrectnessMetric can be implemented in DeepEval’s tracing style using @observe, Golden(expected_tools=...), EvaluationDataset, and evals_iterator(), where actual tool calls are captured automatically from the agent execution.

In [10]:
from deepeval.test_case import LLMTestCase
from deepeval import evaluate
import time

tool_correctness_results = []

for row_index, row in agent_df.iterrows():
    task_completion_test_case = LLMTestCase(
        input=row["user_task"],
        actual_output=row["actual_output"]
    )

    print("Running:", row["test_id"])

    evaluate(
        test_cases=[task_completion_test_case],
        metrics=[task_completion_metric],
        async_config=AsyncConfig(run_async=False),
        error_config=ErrorConfig(ignore_errors=True)
    )

    actual_tool = str(row["actual_tools"]).strip()
    expected_tool = str(row["expected_tools"]).strip()

    tool_correctness_status = "PASS" if actual_tool == expected_tool else "FAIL"

    tool_correctness_results.append({
        "test_id": row["test_id"],
        "user_task": row["user_task"],
        "expected_tool": expected_tool,
        "actual_tool": actual_tool,
        "tool_correctness": tool_correctness_status
    })

    print("Expected tool:", expected_tool)
    print("Actual tool:", actual_tool)
    print("Tool Correctness:", tool_correctness_status)
    print("Completed:", row["test_id"])
    print("-" * 80)

    time.sleep(5)

tool_correctness_df = pd.DataFrame(tool_correctness_results)

display(tool_correctness_df)

print("Task Completion + Tool Correctness evaluation completed.")

Running: AGENT_TC_001

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I placed order ORD1001 yesterday. How can I track where it is now?                     │
│  │     Actual Output:    Order ORD1001 can be tracked using the tracking link sent to your registered email     │
│  │                       or mobile number.                                                                      │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.20  │ 0.60      │ The response only tells the user how to track the order    │
│              │                 │       │           │ via a link, but it does not provide the actual status of   │
│              │                 │       │           │ order ORD1001, which is the core of the requested task.    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.20                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=395835;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1.29s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: track_order_tool
Actual tool: track_order_tool
Tool Correctness: PASS
Completed: AGENT_TC_001
--------------------------------------------------------------------------------
Running: AGENT_TC_002

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.90                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=345611;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1.03s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: refund_policy_tool
Actual tool: refund_policy_tool
Tool Correctness: PASS
Completed: AGENT_TC_002
--------------------------------------------------------------------------------
Running: AGENT_TC_003

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=319241;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.82s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: change_address_tool
Actual tool: change_address_tool
Tool Correctness: PASS
Completed: AGENT_TC_003
--------------------------------------------------------------------------------
Running: AGENT_TC_004

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.90                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=800822;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1.09s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: cancel_order_tool
Actual tool: cancel_order_tool
Tool Correctness: PASS
Completed: AGENT_TC_004
--------------------------------------------------------------------------------
Running: AGENT_TC_005

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.75                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=427932;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.98s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: payment_issue_tool
Actual tool: payment_issue_tool
Tool Correctness: PASS
Completed: AGENT_TC_005
--------------------------------------------------------------------------------
Running: AGENT_TC_006

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I need the invoice for order ORD1006. Where can I download it?                         │
│  │     Actual Output:    You can download the invoice for order ORD1006 from your order history, or contact     │
│  │                       support if it is not visible.                                                          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.20  │ 0.60      │ The system did not provide the requested invoice; it       │
│              │                 │       │           │ only gave instructions on how the user might obtain it     │
│              │                 │       │           │ themselves.                                                │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.20                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=806984;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.88s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: get_invoice_tool
Actual tool: get_invoice_tool
Tool Correctness: PASS
Completed: AGENT_TC_006
--------------------------------------------------------------------------------
Running: AGENT_TC_007

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            When will my order ORD1007 reach Bengaluru?                                            │
│  │     Actual Output:    You can check the estimated delivery date for order ORD1007 on the order tracking      │
│  │                       page for Bengaluru delivery updates.                                                   │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.10  │ 0.60      │ The response does not provide the estimated delivery       │
│              │                 │       │           │ date for order ORD1007; it merely directs the user to      │
│              │                 │       │           │ the tracking page, which fails to fulfill the task.        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.10                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=727091;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.69s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: delivery_estimate_tool
Actual tool: delivery_estimate_tool
Tool Correctness: PASS
Completed: AGENT_TC_007
--------------------------------------------------------------------------------
Running: AGENT_TC_008

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            Before placing an order, I want to know what delivery options are available.           │
│  │     Actual Output:    Available delivery options may include standard delivery and express delivery,         │
│  │                       depending on product availability and delivery location.                               │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.50  │ 0.60      │ The response lists general delivery options (standard      │
│              │                 │       │           │ and express) but does not confirm which ones are           │
│              │                 │       │           │ actually available for the specific product or location,   │
│              │                 │       │           │ so it only partially fulfills the task.                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.50                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=287353;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.85s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: delivery_options_tool
Actual tool: delivery_options_tool
Tool Correctness: PASS
Completed: AGENT_TC_008
--------------------------------------------------------------------------------
Running: AGENT_TC_009

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=449687;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.89s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: human_handoff_tool
Actual tool: human_handoff_tool
Tool Correctness: PASS
Completed: AGENT_TC_009
--------------------------------------------------------------------------------
Running: AGENT_TC_010

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=947578;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.76s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: complaint_tool
Actual tool: complaint_tool
Tool Correctness: PASS
Completed: AGENT_TC_010
--------------------------------------------------------------------------------
Running: AGENT_TC_011

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.80                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=598077;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.82s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: return_request_tool
Actual tool: return_request_tool
Tool Correctness: PASS
Completed: AGENT_TC_011
--------------------------------------------------------------------------------
Running: AGENT_TC_012

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=292733;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1.09s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: refund_timeline_tool
Actual tool: refund_timeline_tool
Tool Correctness: PASS
Completed: AGENT_TC_012
--------------------------------------------------------------------------------
Running: AGENT_TC_013

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I want to update the mobile number in my account.                                      │
│  │     Actual Output:    You can update your mobile number from account settings or profile section.            │
│  │                       Verification may be required to save the change.                                       │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.20  │ 0.60      │ The response only provides instructions on how the user    │
│              │                 │       │           │ can update their mobile number, but it does not actually   │
│              │                 │       │           │ perform the update or confirm that the number was          │
│              │                 │       │           │ changed.                                                   │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.20                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=424008;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 4.22s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: edit_account_tool
Actual tool: edit_account_tool
Tool Correctness: PASS
Completed: AGENT_TC_013
--------------------------------------------------------------------------------
Running: AGENT_TC_014

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.90                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=496993;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.23s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: recover_password_tool
Actual tool: recover_password_tool
Tool Correctness: PASS
Completed: AGENT_TC_014
--------------------------------------------------------------------------------
Running: AGENT_TC_015

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            Is cash on delivery available for my location?                                         │
│  │     Actual Output:    Cash on delivery availability depends on your product and delivery location. You       │
│  │                       can check it during checkout.                                                          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.30  │ 0.60      │ The response explains that cash on delivery availability   │
│              │                 │       │           │ depends on product and location and suggests checking at   │
│              │                 │       │           │ checkout, but it does not provide a definitive             │
│              │                 │       │           │ determination for the user’s specific location, thus       │
│              │                 │       │           │ only partially addressing the task.                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.30                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=420023;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.96s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: payment_methods_tool
Actual tool: payment_methods_tool
Tool Correctness: PASS
Completed: AGENT_TC_015
--------------------------------------------------------------------------------
Running: AGENT_TC_016

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            Will I be charged any fee if I cancel order ORD1016?                                   │
│  │     Actual Output:    Cancellation fee depends on the order status and policy. Please check the              │
│  │                       cancellation details for order ORD1016 before confirming cancellation.                 │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.25  │ 0.60      │ The response does not directly answer whether a            │
│              │                 │       │           │ cancellation fee applies to order ORD1016; it merely       │
│              │                 │       │           │ states that the fee depends on status and policy and       │
│              │                 │       │           │ suggests checking details, leaving the user without a      │
│              │                 │       │           │ definitive determination.                                  │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.25                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=228216;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.12s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: cancellation_fee_tool
Actual tool: cancellation_fee_tool
Tool Correctness: PASS
Completed: AGENT_TC_016
--------------------------------------------------------------------------------
Running: AGENT_TC_017

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I submitted refund request RF1017. How can I check its status?                         │
│  │     Actual Output:    Refund request RF1017 can be tracked from the refund status page or through the        │
│  │                       update sent to your registered email/mobile number.                                    │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.30  │ 0.60      │ The response did not provide the actual status of refund   │
│              │                 │       │           │ request RF1017; it only directed the user to where they    │
│              │                 │       │           │ could check it themselves. This partially addresses the    │
│              │                 │       │           │ request but does not fulfill the user's immediate need     │
│              │                 │       │           │ for the status information.                                │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.30                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=92144;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.99s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: track_refund_tool
Actual tool: track_refund_tool
Tool Correctness: PASS
Completed: AGENT_TC_017
--------------------------------------------------------------------------------
Running: AGENT_TC_018

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=849540;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.1s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: delete_account_tool
Actual tool: delete_account_tool
Tool Correctness: PASS
Completed: AGENT_TC_018
--------------------------------------------------------------------------------
Running: AGENT_TC_019

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            How do I subscribe to order updates and offer notifications?                           │
│  │     Actual Output:    You can subscribe to order and offer notifications from account settings or the        │
│  │                       newsletter subscription option.                                                        │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.30  │ 0.60      │ The response only explains how the user can subscribe to   │
│              │                 │       │           │ order updates and offer notifications, but it does not     │
│              │                 │       │           │ actually perform the subscription or confirm that the      │
│              │                 │       │           │ user has been subscribed. Therefore it partially           │
│              │                 │       │           │ addresses the task but does not fully achieve it.          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.30                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=573479;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.25s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: newsletter_subscription_tool
Actual tool: newsletter_subscription_tool
Tool Correctness: PASS
Completed: AGENT_TC_019
--------------------------------------------------------------------------------
Running: AGENT_TC_020

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.95                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=134816;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 2.86s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: review_tool
Actual tool: review_tool
Tool Correctness: PASS
Completed: AGENT_TC_020
--------------------------------------------------------------------------------
Running: AGENT_TC_021

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I placed order ORD2001 and need to track it now.                                       │
│  │     Actual Output:    You can cancel your order from the cancellation page if it has not shipped.            │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The user requested to track order ORD2001, but the         │
│              │                 │       │           │ response only provided information about canceling the     │
│              │                 │       │           │ order if it has not shipped. No tracking details or        │
│              │                 │       │           │ status updates were given, so the task was not achieved.   │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=145872;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 3.02s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: track_order_tool
Actual tool: cancel_order_tool
Tool Correctness: FAIL
Completed: AGENT_TC_021
--------------------------------------------------------------------------------
Running: AGENT_TC_022

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            My payment was deducted twice for order ORD2002. What should I do?                     │
│  │     Actual Output:    Your order can be tracked from the tracking link sent to your email.                   │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The response does not address the user's double payment    │
│              │                 │       │           │ issue or provide any guidance. It only mentions order      │
│              │                 │       │           │ tracking, which is unrelated to the user's request.        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=633161;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.19s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: payment_issue_tool
Actual tool: track_order_tool
Tool Correctness: FAIL
Completed: AGENT_TC_022
--------------------------------------------------------------------------------
Running: AGENT_TC_023

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I received a damaged product for order ORD2003 and need help.                          │
│  │     Actual Output:    Please restart the app and try placing the order again.                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.10  │ 0.60      │ The response does not address the user's request for       │
│              │                 │       │           │ assistance with a damaged product; it merely suggests      │
│              │                 │       │           │ restarting the app, which is unrelated to resolving the    │
│              │                 │       │           │ issue with order ORD2003.                                  │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.10                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=206458;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1.21s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: complaint_tool
Actual tool: complaint_tool
Tool Correctness: PASS
Completed: AGENT_TC_023
--------------------------------------------------------------------------------
Running: AGENT_TC_024

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            Can I get a refund for a used product after 45 days?                                   │
│  │     Actual Output:    Yes, you can get a full refund immediately without any condition.                      │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The answer incorrectly states that a full refund can be    │
│              │                 │       │           │ obtained immediately without any condition, which does     │
│              │                 │       │           │ not address the specific scenario of a used product        │
│              │                 │       │           │ after 45 days. It fails to determine whether a refund is   │
│              │                 │       │           │ possible under those conditions.                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=646763;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 3.93s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: refund_policy_tool
Actual tool: refund_policy_tool
Tool Correctness: PASS
Completed: AGENT_TC_024
--------------------------------------------------------------------------------
Running: AGENT_TC_025

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 1.00                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=490821;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 3.68s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: change_address_tool
Actual tool: change_address_tool
Tool Correctness: PASS
Completed: AGENT_TC_025
--------------------------------------------------------------------------------
Running: AGENT_TC_026

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I forgot my password and cannot access my account.                                     │
│  │     Actual Output:    Please share your current password so I can reset it for you.                          │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.10  │ 0.60      │ The assistant incorrectly requests the user’s current      │
│              │                 │       │           │ password, which is unnecessary and insecure for a          │
│              │                 │       │           │ forgotten‑password scenario. It fails to provide a         │
│              │                 │       │           │ proper reset procedure, so it does not align with the      │
│              │                 │       │           │ task.                                                      │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.10                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=380529;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.02s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: recover_password_tool
Actual tool: recover_password_tool
Tool Correctness: PASS
Completed: AGENT_TC_026
--------------------------------------------------------------------------------
Running: AGENT_TC_027

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I need invoice for order ORD2007 for reimbursement.                                    │
│  │     Actual Output:    Refunds are processed after return pickup verification.                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.05  │ 0.60      │ The actual response does not provide an invoice for        │
│              │                 │       │           │ order ORD2007; instead it gives a statement about refund   │
│              │                 │       │           │ processing. It fails to meet the requested task.           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.05                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=961312;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.11s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: get_invoice_tool
Actual tool: refund_timeline_tool
Tool Correctness: FAIL
Completed: AGENT_TC_027
--------------------------------------------------------------------------------
Running: AGENT_TC_028

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 0.60                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=242169;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.27s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: payment_methods_tool
Actual tool: payment_methods_tool
Tool Correctness: PASS
Completed: AGENT_TC_028
--------------------------------------------------------------------------------
Running: AGENT_TC_029

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            My refund request RF2029 is pending. Can you check the status?                         │
│  │     Actual Output:    Please check your order tracking page for delivery updates.                            │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The actual outcome does not provide any information        │
│              │                 │       │           │ about the refund request RF2029; it merely directs the     │
│              │                 │       │           │ user to check the order tracking page for delivery         │
│              │                 │       │           │ updates, which is unrelated to the refund status.          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=840629;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.08s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: track_refund_tool
Actual tool: delivery_estimate_tool
Tool Correctness: FAIL
Completed: AGENT_TC_029
--------------------------------------------------------------------------------
Running: AGENT_TC_030

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I want to delete my account permanently. What happens to my data?                      │
│  │     Actual Output:    You can subscribe to newsletters from account settings.                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The response does not address the user's request for       │
│              │                 │       │           │ permanent account deletion or provide any information      │
│              │                 │       │           │ about data handling. Instead, it incorrectly suggests      │
│              │                 │       │           │ subscribing to newsletters, which is irrelevant to the     │
│              │                 │       │           │ task.                                                      │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=143859;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.84s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: delete_account_tool
Actual tool: newsletter_subscription_tool
Tool Correctness: FAIL
Completed: AGENT_TC_030
--------------------------------------------------------------------------------
Running: AGENT_TC_031

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            My return pickup is done, but I have not received the refund yet.                      │
│  │     Actual Output:    Return pickup can be scheduled from the order page.                                    │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.05  │ 0.60      │ The response does not address the user's question about    │
│              │                 │       │           │ the missing refund; it merely provides information about   │
│              │                 │       │           │ scheduling a return pickup, which is unrelated to the      │
│              │                 │       │           │ refund issue.                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.05                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=106491;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.0s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: refund_timeline_tool
Actual tool: return_request_tool
Tool Correctness: FAIL
Completed: AGENT_TC_031
--------------------------------------------------------------------------------
Running: AGENT_TC_032

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I want to speak with a human agent because my issue is urgent.                         │
│  │     Actual Output:    Here are the delivery options available for your order.                                │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The user explicitly asked to speak with a human agent      │
│              │                 │       │           │ due to an urgent issue, but the system instead offered     │
│              │                 │       │           │ delivery options for an order, which does not address      │
│              │                 │       │           │ the user's request.                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=670094;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 6.5s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: human_handoff_tool
Actual tool: delivery_options_tool
Tool Correctness: FAIL
Completed: AGENT_TC_032
--------------------------------------------------------------------------------
Running: AGENT_TC_033

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Task Completion           │ 1.00                  │ 100.00% | passed=1 | failed=0                  │ 1         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=626500;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.77s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: cancel_order_tool
Actual tool: cancel_order_tool
Tool Correctness: PASS
Completed: AGENT_TC_033
--------------------------------------------------------------------------------
Running: AGENT_TC_034

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I want to update the email address linked to my account.                               │
│  │     Actual Output:    You can leave a product review after delivery from the product page.                   │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.00  │ 0.60      │ The response does not address updating the user's email    │
│              │                 │       │           │ address at all; it instead provides instructions for       │
│              │                 │       │           │ leaving a product review, which is unrelated to the        │
│              │                 │       │           │ requested task.                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.00                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=704283;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 4.05s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: edit_account_tool
Actual tool: review_tool
Tool Correctness: FAIL
Completed: AGENT_TC_034
--------------------------------------------------------------------------------
Running: AGENT_TC_035

✨ You're running DeepEval's latest Task Completion Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=False)...

Output()

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_0                                                                                                 │
│  ├──   Input:            I received my order and want to post a product review.                                 │
│  │     Actual Output:    Please contact payment support with your transaction ID.                               │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric          ┃ Score ┃ Threshold ┃ Reason                                                     │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Task Completion │ 0.10  │ 0.60      │ The user requested to post a product review, but the       │
│              │                 │       │           │ system incorrectly advised them to contact payment         │
│              │                 │       │           │ support with a transaction ID, which does not address      │
│              │                 │       │           │ the review request.                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score          ┃ Pass Rate                                    ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Task Completion           │ 0.10                   │ 0.00% | passed=0 | failed=1                  │ 1          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=749247;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.94s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Expected tool: review_tool
Actual tool: payment_issue_tool
Tool Correctness: FAIL
Completed: AGENT_TC_035
--------------------------------------------------------------------------------

,test_id,user_task,expected_tool,actual_tool,tool_correctness
0,AGENT_TC_001,I placed order ORD1001 yesterday. How can I tr...,track_order_tool,track_order_tool,PASS
1,AGENT_TC_002,The product is unused and I bought it 15 days ...,refund_policy_tool,refund_policy_tool,PASS
2,AGENT_TC_003,My order ORD1003 has not shipped yet. I need t...,change_address_tool,change_address_tool,PASS
3,AGENT_TC_004,"I already paid for ORD1004, but it has not bee...",cancel_order_tool,cancel_order_tool,PASS
4,AGENT_TC_005,"Money was deducted from my account, but I did ...",payment_issue_tool,payment_issue_tool,PASS
5,AGENT_TC_006,I need the invoice for order ORD1006. Where ca...,get_invoice_tool,get_invoice_tool,PASS
6,AGENT_TC_007,When will my order ORD1007 reach Bengaluru?,delivery_estimate_tool,delivery_estimate_tool,PASS
7,AGENT_TC_008,"Before placing an order, I want to know what d...",delivery_options_tool,delivery_options_tool,PASS
8,AGENT_TC_009,My order is delayed and I want to talk to a re...,human_handoff_tool,human_handoff_tool,PASS
9,AGENT_TC_010,The product I received is damaged. How do I ra...,complaint_tool,complaint_tool,PASS
10,AGENT_TC_011,The item does not fit me. How can I return it?,return_request_tool,return_request_tool,PASS
11,AGENT_TC_012,My return pickup is completed. When will I rec...,refund_timeline_tool,refund_timeline_tool,PASS
12,AGENT_TC_013,I want to update the mobile number in my account.,edit_account_tool,edit_account_tool,PASS
13,AGENT_TC_014,I forgot my password and cannot log in to my a...,recover_password_tool,recover_password_tool,PASS
14,AGENT_TC_015,Is cash on delivery available for my location?,payment_methods_tool,payment_methods_tool,PASS
15,AGENT_TC_016,Will I be charged any fee if I cancel order OR...,cancellation_fee_tool,cancellation_fee_tool,PASS
16,AGENT_TC_017,I submitted refund request RF1017. How can I c...,track_refund_tool,track_refund_tool,PASS
17,AGENT_TC_018,I want to permanently delete my account.,delete_account_tool,delete_account_tool,PASS
18,AGENT_TC_019,How do I subscribe to order updates and offer ...,newsletter_subscription_tool,newsletter_subscription_tool,PASS
19,AGENT_TC_020,I received my product and want to leave a revi...,review_tool,review_tool,PASS
20,AGENT_TC_021,I placed order ORD2001 and need to track it now.,track_order_tool,cancel_order_tool,FAIL
21,AGENT_TC_022,My payment was deducted twice for order ORD200...,payment_issue_tool,track_order_tool,FAIL
22,AGENT_TC_023,I received a damaged product for order ORD2003...,complaint_tool,complaint_tool,PASS
23,AGENT_TC_024,Can I get a refund for a used product after 45...,refund_policy_tool,refund_policy_tool,PASS
24,AGENT_TC_025,I want to change the delivery address for orde...,change_address_tool,change_address_tool,PASS
25,AGENT_TC_026,I forgot my password and cannot access my acco...,recover_password_tool,recover_password_tool,PASS
26,AGENT_TC_027,I need invoice for order ORD2007 for reimburse...,get_invoice_tool,refund_timeline_tool,FAIL
27,AGENT_TC_028,Is cash on delivery available for pincode 560001?,payment_methods_tool,payment_methods_tool,PASS
28,AGENT_TC_029,My refund request RF2029 is pending. Can you c...,track_refund_tool,delivery_estimate_tool,FAIL
29,AGENT_TC_030,I want to delete my account permanently. What ...,delete_account_tool,newsletter_subscription_tool,FAIL
30,AGENT_TC_031,"My return pickup is done, but I have not recei...",refund_timeline_tool,return_request_tool,FAIL
31,AGENT_TC_032,I want to speak with a human agent because my ...,human_handoff_tool,delivery_options_tool,FAIL
32,AGENT_TC_033,Can I cancel order ORD2033 after it has alread...,cancel_order_tool,cancel_order_tool,PASS
33,AGENT_TC_034,I want to update the email address linked to m...,edit_account_tool,review_tool,FAIL
34,AGENT_TC_035,I received my order and want to post a product...,review_tool,payment_issue_tool,FAIL

Task Completion + Tool Correctness evaluation completed.

StepEfficiencyMetric

StepEfficiencyMetric checks whether an AI agent completed the task using useful and necessary steps.

It focuses on the agent’s execution path.

If the agent uses direct and relevant steps, it passes.

If the agent uses unnecessary, repeated, or unrelated steps, it fails.

In [ ]:
step_efficiency_metric = StepEfficiencyMetric(
    threshold=0.6,
    model=groq_model,
    include_reason=True
)

print("Step Efficiency metric created.")

Step Efficiency metric created.

In [ ]:
for golden in agent_dataset.evals_iterator(
    metrics=[step_efficiency_metric],
    error_config=ErrorConfig(ignore_errors=True),
    async_config=AsyncConfig(run_async=False)
):
    answer = customer_support_agent(golden.input)

    print("Task:", golden.input)
    print("Agent answer:", answer)
    print("-" * 80)

print("Agentic Step Efficiency evaluation completed.")

Output()

Task: Help the customer track their order.

Agent answer: Order can be tracked using the tracking link sent to the registered email or mobile number.

--------------------------------------------------------------------------------

Task: Help the customer understand the refund policy.

Agent answer: Refund is allowed within 15 days if the item is unused and in original condition.

--------------------------------------------------------------------------------

Task: Help the customer change their delivery address before shipment.

Agent answer: Delivery address can be changed before shipment by contacting customer support.

--------------------------------------------------------------------------------

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                    ┃ Average Score         ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Step Efficiency           │ 1.00                  │ 100.00% | passed=3 | failed=0                  │ 3         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=338782;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 36.59s | token cost: None)
» Test Results (3 total tests):
   » Pass Rate: 100.0% | Passed: 3 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Agentic Step Efficiency evaluation completed.

ToolCorrectnessMetric

ToolCorrectnessMetric checks whether an AI agent selected the correct tool for the given task.

It compares the tools actually used by the agent with the tools expected for that task.

If the agent calls the correct tool, it passes.

If the agent calls the wrong tool, misses a required tool, or uses an unnecessary tool, it fails.

In [ ]:
from deepeval.test_case import LLMTestCase, ToolCall
from deepeval import evaluate

In [ ]:
tool_correctness_metric = ToolCorrectnessMetric(
    threshold=0.6
)

print("Tool Correctness metric created.")
# ToolCorrectnessMetric can compare expected tool and actual tool directly.

Tool Correctness metric created.

✨ You're running DeepEval's latest Tool Correctness Metric! (using None, strict=False, async_mode=True)...

Output()

INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                     ┃ Average Score         ┃ Pass Rate                                     ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Tool Correctness           │ 1.00                  │ 100.00% | passed=3 | failed=0                 │ 3         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=970323;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 0.15s | token cost: None)
» Test Results (3 total tests):
   » Pass Rate: 100.0% | Passed: 3 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Tool Correctness evaluation completed.

ArgumentCorrectnessMetric

ArgumentCorrectnessMetric checks whether an AI agent passed the correct arguments or input values into the selected tool.

It is used after checking tool correctness.

If the agent selects the correct tool but passes wrong, missing, or incomplete arguments, this metric can fail.

Example:
If the task is “Track order ORD123”, the agent should call the tracking tool with order_id = "ORD123".

If the agent calls the tracking tool without the order ID, the tool choice is correct, but the argument is wrong.

In [ ]:
argument_correctness_metric = ArgumentCorrectnessMetric(
    threshold=0.6,
    model=groq_model,
    include_reason=True
)

print("Argument Correctness metric created.")

Argument Correctness metric created.

In [ ]:
argument_test_cases = [
    LLMTestCase(
        input="Track order ORD123.",
        actual_output="Order ORD123 can be tracked using the tracking link.",
        tools_called=[
            ToolCall(
                name="track_order_tool",
                input_parameters={"order_id": "ORD123"}
            )
        ]
    ),
    LLMTestCase(
        input="Check refund policy for order ORD456.",
        actual_output="Order ORD456 is eligible for refund if it is within 15 days and unused.",
        tools_called=[
            ToolCall(
                name="refund_policy_tool",
                input_parameters={"order_id": "ORD456"}
            )
        ]
    ),
    LLMTestCase(
        input="Change delivery address for order ORD789.",
        actual_output="Delivery address for order ORD789 can be changed before shipment.",
        tools_called=[
            ToolCall(
                name="change_address_tool",
                input_parameters={"order_id": "ORD789"}
            )
        ]
    )
]

evaluate(
    test_cases=argument_test_cases,
    metrics=[argument_correctness_metric]
)

print("Argument Correctness evaluation completed.")

✨ You're running DeepEval's latest Argument Correctness Metric! (using openai/gpt-oss-20b, strict=False,
async_mode=True)...

Output()

INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute.e2e:in _a_execute_llm_test_cases

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_0 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                 │
│  ❌ test_case_2                                                                                                 │
│  ├──   Input:            Change delivery address for order ORD789.                                              │
│  │     Actual Output:    Delivery address for order ORD789 can be changed before shipment.                      │
│  └── Metrics                                                                                                    │
│       Status ┃ Metric               ┃ Score ┃ Threshold ┃ Reason                                                │
│      ━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  │
│        FAIL  │ Argument Correctness │ 0.00  │ 0.60      │ The score is 0.00 because the input only provides     │
│              │                      │       │           │ the order ID but does not include the new delivery    │
│              │                      │       │           │ address required to change the address.               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                          ┃ Average Score        ┃ Pass Rate                                 ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Argument Correctness            │ 0.67                 │ 66.67% | passed=2 | failed=1              │ 3         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=98596;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 2.38s | token cost: None)
» Test Results (3 total tests):
   » Pass Rate: 66.67% | Passed: 2 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Argument Correctness evaluation completed.

PlanQualityMetric

PlanQualityMetric checks whether an AI agent created a good plan before doing the task.

It focuses on the quality of the planned steps.

A good plan should be clear, logical, complete, and useful for completing the user’s task.

If the plan is missing important steps, has unnecessary steps, or is not useful for the task, this metric can fail.

In [ ]:
plan_quality_metric = PlanQualityMetric(
    threshold=0.6,
    model=groq_model,
    include_reason=True
)

print("Plan Quality metric created.")

Plan Quality metric created.

In [ ]:
@observe()
def planned_customer_support_agent(user_task):
    plan = [
        "Identify the customer support request.",
        "Select the correct support tool.",
        "Use the tool result to answer the customer."
    ]

    if "track" in user_task.lower():
        answer = track_order_tool()

    elif "refund" in user_task.lower():
        answer = refund_policy_tool()

    elif "delivery address" in user_task.lower() or "address" in user_task.lower():
        answer = change_address_tool()

    else:
        answer = "I could not identify the correct support action."

    update_current_trace(
        input=user_task,
        output=answer,
        metadata={
            "plan": plan
        }
    )

    return answer

In [ ]:
for golden in agent_dataset.evals_iterator(
    metrics=[plan_quality_metric],
    error_config=ErrorConfig(ignore_errors=True),
    async_config=AsyncConfig(run_async=False)
):
    answer = planned_customer_support_agent(golden.input)

    print("Task:", golden.input)
    print("Agent answer:", answer)
    print("-" * 80)

print("Plan Quality evaluation completed.")

Output()

Task: Help the customer track their order.

Agent answer: Order can be tracked using the tracking link sent to the registered email or mobile number.

--------------------------------------------------------------------------------

Task: Help the customer understand the refund policy.

Agent answer: Refund is allowed within 15 days if the item is unused and in original condition.

--------------------------------------------------------------------------------

Task: Help the customer change their delivery address before shipment.

Agent answer: Delivery address can be changed before shipment by contacting customer support.

--------------------------------------------------------------------------------

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                ┃ Average Score           ┃ Pass Rate                                       ┃ Total      │
│ ━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━ │
│  Plan Quality          │ 1.00                    │ 100.00% | passed=3 | failed=0                   │ 3          │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=677934;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 2.66s | token cost: None)
» Test Results (3 total tests):
   » Pass Rate: 100.0% | Passed: 3 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Plan Quality evaluation completed.

PlanAdherenceMetric

PlanAdherenceMetric checks whether an AI agent followed the plan it created.

It compares the planned steps with the actual steps taken by the agent.

If the agent follows the planned steps properly, it passes.

If the agent skips planned steps, does different steps, or goes away from the plan, this metric can fail.

In [ ]:
plan_adherence_metric = PlanAdherenceMetric(
    threshold=0.6,
    model=groq_model,
    include_reason=True
)

print("Plan Adherence metric created.")

Plan Adherence metric created.

In [ ]:
for golden in agent_dataset.evals_iterator(
    metrics=[plan_adherence_metric],
    error_config=ErrorConfig(ignore_errors=True),
    async_config=AsyncConfig(run_async=False)
):
    answer = planned_customer_support_agent(golden.input)

    print("Task:", golden.input)
    print("Agent answer:", answer)
    print("-" * 80)

print("Plan Adherence evaluation completed.")

Output()

Task: Help the customer track their order.

Agent answer: Order can be tracked using the tracking link sent to the registered email or mobile number.

--------------------------------------------------------------------------------

Task: Help the customer understand the refund policy.

Task: Help the customer change their delivery address before shipment.

Agent answer: Delivery address can be changed before shipment by contacting customer support.

--------------------------------------------------------------------------------

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 🚀 DeepEval Evaluation Results                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_1 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_2 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✅ test_case_3 (Passed 1 metrics)                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Aggregate Metrics                                                                                               │
│                                                                                                                 │
│  Metric                   ┃ Average Score          ┃ Pass Rate                                      ┃ Total     │
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━ │
│  Plan Adherence           │ 1.00                   │ 100.00% | passed=3 | failed=0                  │ 3         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

⚠ WARNING: No hyperparameters logged.
» ]8;id=249628;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 2.81s | token cost: None)
» Test Results (3 total tests):
   » Pass Rate: 100.0% | Passed: 3 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

Plan Adherence evaluation completed.